### ISSUE TITLE
About PEP8

### ISSUE THREAD

**Issue by Yardanico** [vanjac/three#85]
Why did you named all methods in CamelCase instead of Python's snake_case?
Just curious.

**Comment by TiberiumPY** [comment]
Other things:
Why are you using hand-made argument parsing instead of using argparse?
It's in standart library in Python 3.2+ and Python 2.7

**Comment by vanjac** [comment]
No particular reason for CamelCase, that's just my preference and what I'm used to.

I didn't know about argparse before though. That could make three.py a bit cleaner.
